### ISSUE TITLE
what is status of this project

### ISSUE THREAD

**Issue by 0xHexE** [Hikari-no-Tenshi/android_device_oneplus_guacamoleb#1]
I am trying to port halium to OnePlus 7.
Is this ready?

**Comment by Hikari-no-Tenshi** [comment]
What do you mean by "Is this ready?
10.0 branch is latest and used by me to build crDroid Android 6.3.
lineage-17.1 branch is outdated but had no issues in past when i was building LineageOS 17.1.

**Comment by 0xHexE** [comment]
Thanks
You last updated 8 hr back so I think this is in development.
That's all.
